image: gitpod/workspace-full

tasks:
  - name: Install toolchain + start SQL Server
    init: |
      sudo apt-get update
      sudo apt-get install -y ca-certificates curl gnupg

      # Install .NET 8 SDK
      wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y dotnet-sdk-8.0

      # Install Node.js (LTS)
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Ensure docker compose is available (workspace-full usually has docker, but ensure plugin)
      sudo apt-get install -y docker-compose-plugin || true

      # Create local env file if missing (you will customize password)
      if [ ! -f .env ]; then
        cp .env.example .env
      fi

      dotnet restore
    command: |
      docker compose up -d
      echo "SQL Server container started. You can now run the API."
